name: Python Tools

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VITUALENV: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Instalar Pipenv e Codecov
        run: |
          pip install -q pipenv codecov

      - name: Instalar Dependências
        run: |
          pipenv sync -d
          pip install safety

      - name: Rodar Flake8
        run: |
          pipenv run flake8

      - name: Rodar Testes
        run: |
          pipenv run pytest libpythonpro --cov=libpythonpro

      - name: Relatorio Codecove
        run: |
          codecov

      - name: Run Security check with PyUp
        env:
          SAFETY_API_KEY: ${{secrets.SAFETY_API_KEY}}
        run: safety check --key $SAFETY_API_KEY
        continue-on-error: false
